### ISSUE TITLE
Use Case Suggestion: How to passing Multiple Arguments to a function in JavaScript

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#144] opened 2018-04-24 12:04 UTC
var printMultipleTimes = function (howManyTimes, whatToDraw) {
      for (var i = 0; i < howManyTimes; i++) {  
      console.log(i + " " + whatToDraw); 
 } 
};
printMultipleTimes(5, "=^.^=");
 //0 =^.^=
 //1 =^.^= 
//2 =^.^=
 //3 =^.^=
 //4 =^.^=

**Comment by jadjoubran** [comment] 2018-04-24 16:15
Thanks @politologu 
This is a duplicate of your previous issue here #140

**Closed by jadjoubran** 2018-04-24 16:15 UTC
Labels: duplicate

**Comment by politologu** [comment] 2018-04-24 16:25
@jadjoubran  omg sorry

**Comment by jadjoubran** [comment] 2018-04-24 16:27
No worries 👍
