### ISSUE TITLE
Use Case Suggestion:

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#12] opened 2017-12-16 18:45 UTC
I'm thinking about this use case:

Which is the difference between var, let and const in JavaScript? 

Thanks!

**Comment by kissu** [comment] 2017-12-16 18:53
Already posted in #10 no ?

**Comment by jadjoubran** [comment] 2017-12-16 20:28
yep, that's a duplicate of #10

**Closed by jadjoubran** 2017-12-16 20:28 UTC
Labels: duplicate
